algoritmo "exercicio88"
var
   M: Caractere
   Q: Inteiro
Procedimento Gerador()
Var
   C: Inteiro
Inicio
      EscrevaL("+-----=====================-----+")
      Para C <- 1 ate Q faca
           EscrevaL(M)
      FimPara
      EscrevaL("+-----=====================-----+")
FimProcedimento

inicio
      M <- "       APRENDENDO PORTUGOL       "
      Q <- 4
      Gerador()

fimalgoritmo
