algoritmo "exercicio67"
var
   C, V: Inteiro
inicio

      EscrevaL("-----------------------")
      EscrevaL("  CONTAGEM DE A ATE B  ")
      EscrevaL("-----------------------")
      EscrevaL("")
      
      Escreva("Digite um valor:  ")
      Leia(V)
      EscrevaL("")
      
      Para C <- 0 ate V faca
           Escreva(C)
      FimPara
      Escreva(", FIM!")
fimalgoritmo