algoritmo "exercicio16"
var
   C, A, MV: Inteiro
inicio
      escrevaL("TEMPO DE VIDA - FUMANTE")
      escrevaL("")
      escreva("Quantidade de CIGARROS FUMADOS/DIA: ")
      leia(C)
      escreva("Quantidade de ANOS COMO FUMANTE: ")
      leia(A)
      
      MV <- C * 10
      
Calcule quantos dias de vida um fumante perderá e exiba o total em dias.
      escrevaL("")
      escreva("Minutos perdidos: ", MV)
      
      
fimalgoritmo