algoritmo "exercicio41"
var
   C: Inteiro
inicio
      C <- 100
      
      escrevaL("----------------------------------")
      escrevaL("  CONTAGEM DECRESCENTE DE 5 EM 5  ")
      escrevaL("----------------------------------")
      
      Enquanto (C >= 5) faca
               escreva(C)
               C <- C - 5
      FimEnquanto
      
      escrevaL(" ... 0")
      escrevaL("Acabou!")
fimalgoritmo