algoritmo "exercicio61"
var
   C: Inteiro
inicio
      C <- 0
      
      EscrevaL("-------------------------------")
      EscrevaL("  CONTAGEM DE 3 EM 3 - REPITA  ")
      EscrevaL("-------------------------------")
      EscrevaL("")
      
      Repita
            Escreva(C)
            C <- C + 3
      Ate (C > 30)
      
      EscrevaL("")
      EscrevaL("")
      Escreva("Fim da contagem")
      Escreva(".")
      Escreva(".")
      Escreva(".")
fimalgoritmo