algoritmo "exercicio40"
var
   C: Inteiro
inicio
      C <- 0
      
      escrevaL("-----------------------------")
      escrevaL("  CONTAGEM DE 3 EM 3 ATÉ 18  ")
      escrevaL("-----------------------------")
      
      Enquanto (C <= 18) faca
               escreva(C)
               C <- C + 3
      FimEnquanto
      
      escrevaL("")
      escrevaL("Acabou!")
fimalgoritmo